# Generated by Django 5.2.7 on 2025-10-08 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('f1', 'Formula 1/FIA'), ('team', 'Team'), ('driver', 'Driver'), ('constructor', 'Constructor'), ('race', 'Race'), ('analysis', 'Analysis'), ('history', 'F1 History'), ('fanbase', 'F1 Fanbase'), ('exclusive', 'Exclusive'), ('other', 'Other')], default='update', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('news_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
        ),
    ]
