# Generated by Django 5.2.7 on 2025-10-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('f1', 'Formula 1/FIA'), ('championship', 'Championship'), ('team', 'Team'), ('driver', 'Driver'), ('constructor', 'Constructor'), ('race', 'Race'), ('analysis', 'Analysis'), ('history', 'F1 History'), ('fanbase', 'F1 Fanbase'), ('exclusive', 'Exclusive'), ('other', 'Other')], default='update', max_length=20),
        ),
    ]
