# Generated by Django 5.2.7 on 2025-10-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_category'),
        ('news', '0003_alter_news_thumbnail'),
    ]

    operations = [
    ]
