# Generated by Django 5.2.6 on 2025-10-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_category'),
        ('news', '0003_alter_news_thumbnail'),
    ]

    operations = [
    ]
