# Generated by Django 5.2.7 on 2025-10-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_id',
            new_name='news',
        ),
    ]
