# Generated by Django 5.2.7 on 2025-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_news_id_comment_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
