# Generated by Django 5.2.6 on 2025-10-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20251021_1736'),
        ('news', '0007_news_news_comments'),
    ]

    operations = [
    ]
