# Generated by Django 5.2.7 on 2025-10-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20251021_2021'),
        ('news', '0008_merge_20251022_1601'),
    ]

    operations = [
    ]
