# Generated by Django 5.2.6 on 2025-10-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20251022_1413'),
        ('news', '0008_merge_20251022_1601'),
    ]

    operations = [
    ]
