# Generated by Django 5.2.7 on 2025-10-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_merge_20251022_1949'),
        ('news', '0009_merge_20251022_2028'),
    ]

    operations = [
    ]
