# Generated by Django 5.2.6 on 2025-10-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_merge_20251023_1007'),
        ('news', '0010_merge_20251023_1036'),
    ]

    operations = [
    ]
