# Generated by Django 5.2.6 on 2025-10-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('base', models.CharField(blank=True, max_length=100)),
                ('team_chief', models.CharField(blank=True, max_length=100)),
                ('technical_chief', models.CharField(blank=True, max_length=100)),
                ('chassis', models.CharField(blank=True, max_length=100)),
                ('power_unit', models.CharField(blank=True, max_length=100)),
                ('first_team_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('world_championships', models.PositiveIntegerField(default=0)),
                ('pole_positions', models.PositiveIntegerField(default=0)),
                ('fastest_laps', models.PositiveIntegerField(default=0)),
                ('highest_race_finish', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, unique=True)),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('place_of_birth', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('grands_prix_entered', models.PositiveIntegerField(default=0)),
                ('highest_grid_position', models.PositiveIntegerField(default=0)),
                ('highest_race_finish', models.CharField(blank=True, max_length=50)),
                ('podiums', models.PositiveIntegerField(default=0)),
                ('points', models.FloatField(default=0.0)),
                ('world_championships', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='information.team')),
            ],
        ),
    ]
