# Generated by Django 5.2.7 on 2025-10-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('long_name', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('circuit_image', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='highest_grid_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='information.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('round_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='information.circuit')),
            ],
            options={
                'ordering': ['season', 'round_number'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('points', models.FloatField(default=0.0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='information.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'team')},
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('points', models.FloatField(default=0.0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='information.driver')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='DriverRaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.PositiveIntegerField(blank=True, null=True)),
                ('finish_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('RET', 'Retired'), ('DNF', 'DNF'), ('DSQ', 'Disqualified'), ('DNS', 'DNS'), ('WD', 'Withdrawn')], default='FINISHED', max_length=10)),
                ('points_awarded', models.FloatField(default=0.0)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('laps', models.PositiveIntegerField(blank=True, null=True)),
                ('time_text', models.CharField(blank=True, max_length=64)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_results', to='information.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_results', to='information.team')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_results', to='information.race')),
            ],
            options={
                'ordering': ['race__round_number', 'finish_position'],
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
