# Generated by Django 5.2.6 on 2025-10-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_circuit_driver_driver_image_driver_number_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverstanding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='driverstanding',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='circuit_image',
        ),
        migrations.AlterField(
            model_name='driverraceresult',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='information.driver'),
        ),
        migrations.DeleteModel(
            name='ConstructorStanding',
        ),
        migrations.DeleteModel(
            name='DriverStanding',
        ),
    ]
