# Generated by Django 5.2.6 on 2025-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_driver_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_image',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_image',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='driverraceresult',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('DQ', 'Disqualified'), ('DNS', 'DNS'), ('WD', 'Withdrawn'), ('NC', 'Not Classified')], default='FINISHED', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
