# Generated by Django 5.2.6 on 2025-10-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('forums_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('forums_views', models.PositiveIntegerField(default=0)),
                ('forums_likes', models.PositiveIntegerField(default=0)),
                ('forums_replies_counts', models.PositiveIntegerField(default=0)),
                ('is_hot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumsReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies_content', models.TextField()),
                ('forums_replies_likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forums_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forums.forums')),
            ],
        ),
    ]
