# Generated by Django 5.2.6 on 2025-10-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forums_user_forumsreplies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsreplies',
            name='forums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to='forums.forums'),
        ),
    ]
