# Generated by Django 5.2.6 on 2025-10-23 03:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_forumsreplies_forums_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forums',
            name='forums_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
