# Generated by Django 5.2.6 on 2025-10-23 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_forums_forums_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsreplies',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reply_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forums',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forums',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumsreplies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
