# Generated by Django 5.2.6 on 2025-10-23 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_forums_likes_forumsreplies_likes_alter_forums_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='forumsreplies',
            name='likes',
        ),
        migrations.AlterField(
            model_name='forums',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='forums',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumsreplies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
