# Generated by Django 5.2.6 on 2025-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_remove_forums_likes_remove_forumsreplies_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
