# Generated by Django 5.2.6 on 2025-10-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_forums_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumsreplies',
            old_name='forums_id',
            new_name='forums',
        ),
    ]
