# Generated by Django 5.2.6 on 2025-10-23 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_rename_forums_id_forumsreplies_forums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='forums_likes',
        ),
        migrations.RemoveField(
            model_name='forumsreplies',
            name='forums_replies_likes',
        ),
        migrations.AddField(
            model_name='forums',
            name='forums_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsreplies',
            name='forums_replies_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
