# Generated by Django 5.2.6 on 2025-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podiums', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=150)),
                ('car', models.CharField(max_length=150)),
                ('points', models.FloatField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
