# Generated by Django 5.2.6 on 2025-10-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
