# Generated by Django 5.2.6 on 2025-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_driver_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('winner', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=150)),
                ('laps', models.FloatField()),
                ('time', models.CharField(max_length=100)),
                ('name_code', models.CharField(blank=True, max_length=10, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
