# Generated by Django 5.2.6 on 2025-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='laps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
