# Generated by Django 5.2.6 on 2025-10-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_winner_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.CharField(max_length=255),
        ),
    ]
